### ISSUE TITLE
No editor features in new workflow file

### ISSUE THREAD

**Issue by melink14** [cschleiden/vscode-github-actions#47] opened 2020-09-14 12:24 UTC
I wanted to create a new workflow using the autocomplete and hover help features but it seems like they don't work in my new workflow file even though they work in pre-existing ones.

I can see a stack trace whenever I go to a new line and start typing a keyword:

```
stack trace: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	at Ct (/home/espeed/.vscode-server-insiders/extensions/cschleiden.vscode-github-actions-0.8.1/dist/extension.js:1:407334)
	at n (/home/espeed/.vscode-server-insiders/extensions/cschleiden.vscode-github-actions-0.8.1/dist/extension.js:1:411503)
	at /home/espeed/.vscode-server-insiders/extensions/cschleiden.vscode-github-actions-0.8.1/dist/extension.js:1:412477
	at yt (/home/espeed/.vscode-server-insiders/extensions/cschleiden.vscode-github-actions-0.8.1/dist/extension.js:1:408282)
	at Et (/home/espeed/.vscode-server-insiders/extensions/cschleiden.vscode-github-actions-0.8.1/dist/extension.js:1:409277)
	at /home/espeed/.vscode-server-insiders/extensions/cschleiden.vscode-github-actions-0.8.1/dist/extension.js:1:411740
	at /home/espeed/.vscode-server-insiders/extensions/cschleiden.vscode-github-actions-0.8.1/dist/extension.js:1:411793
	at /home/espeed/.vscode-server-insiders/extensions/cschleiden.vscode-github-actions-0.8.1/dist/extension.js:1:411840
	at t (/home/espeed/.vscode-server-insiders/extensions/cschleiden.vscode-github-actions-0.8.1/dist/extension.js:1:407422)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by cschleiden** [comment] 2020-09-16 00:27
Yikes, thanks for reporting. I can repro, something doesn't look quite right here.

**Comment by melink14** [comment] 2020-09-16 00:49
Eventually after I finished I was able to get some autocomplete to work.

One idea I had is that the incomplete files were not parsable and that prevented everything else from working.

**Comment by cschleiden** [comment] 2020-11-16 04:21
I'm having a hard-time reproducing this with the latest version, everything works for me now:
![image](https://user-images.githubusercontent.com/2201819/99212559-30071600-2780-11eb-9d86-286b161bfdf5.png)

Closing this for now.

**Closed by cschleiden** 2020-11-16 04:21 UTC
Labels: bug
