### ISSUE TITLE
Dancing progress indicator

### ISSUE THREAD

**Issue by lexfrei** [cschleiden/vscode-github-actions#88] opened 2021-05-06 20:20 UTC
Is this expected?

https://user-images.githubusercontent.com/1366514/117359372-fc4fb200-aebf-11eb-898a-c2f1233f5897.mov

Versions:
Mac OS: 11.3.1
Extension: 0.17.0
VS Code:
```
  Version: 1.56.0
  Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
  Date: 2021-05-04T22:06:21.189Z
  Electron: 12.0.4
  Chrome: 89.0.4389.114
  Node.js: 14.16.0
  V8: 8.9.255.24-electron.0
  OS: Darwin x64 20.4.0
```

P.S.:
Suggested music: https://www.youtube.com/watch?v=PGNiXGX2nLU

**Comment by cschleiden** [comment] 2021-05-07 17:35
Thanks for reporting. This is a duplicate of: https://github.com/cschleiden/vscode-github-actions/issues/76 but I just saw that this should be fixed in the next `code-insiders` release.

**Closed by cschleiden** 2021-05-07 17:35 UTC
