### ISSUE TITLE
Loading animation looks broken

### ISSUE THREAD

**Issue by LinqLover** [cschleiden/vscode-github-actions#90] opened 2021-05-12 21:42 UTC
![vscode-github-actions-loading-animation-ill](https://user-images.githubusercontent.com/38782922/118047806-9a89bf00-b37b-11eb-82bf-d1e15822e5b6.gif)

Apart from that, the extension is great! :-)

**Comment by cschleiden** [comment] 2021-05-13 00:37
Thanks for reporting! Dupe of https://github.com/cschleiden/vscode-github-actions/issues/76 which should be fixed with the next VS Code release 🤞

**Closed by cschleiden** 2021-05-13 00:37 UTC
