### ISSUE TITLE
Running icon animation

### ISSUE THREAD

**Issue by AlariCode** [cschleiden/vscode-github-actions#83] opened 2021-04-02 13:48 UTC
Hello! While running pipeline icon is not animating correctly. It is spinning not from the center but the edge.
![image](https://user-images.githubusercontent.com/2528600/113420862-c015c700-93d2-11eb-9c9c-86a520ee49f1.png)

Mac OS 11.2
VCCode version: 1.55.0

**Comment by cschleiden** [comment] 2021-04-02 15:40
Thanks for reporting, this is a duplicate of https://github.com/cschleiden/vscode-github-actions/issues/76, and unfortunately needs a fix in VS Code itself.

**Closed by cschleiden** 2021-04-02 15:40 UTC
